services:
  # Backend API
  - type: web
    name: oshi-quiz-api
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 -b 0.0.0.0:$PORT src.main:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.11.0

  # Frontend Static Site
  - type: web
    name: oshi-quiz-frontend
    env: static
    region: oregon
    plan: free
    buildCommand: cd frontend && pnpm install && pnpm run build
    staticPublishPath: frontend/dist
    envVars:
      - key: NODE_VERSION
        value: 18

